### PR TITLE
[Docs] New docs

### PR DESCRIPTION
**Pull request by khairulhaaziq**
Dev setup:

1. `cd docs`
2. `pnpm i && pnpm run docs:dev`

### CODE REVIEW

**Comment by zernonia** [comment]
- pushed a fix to tailwindcss causing super slow start time.
- added some cmmand in root package.json to run `docs` client easily

```
pnpm docs:install
pnpm docs:dev
```

**Review by zernonia — COMMENTED** [review]
@khairulhaaziq  Why do we merged this ya? This messed up more responsive ui

**Comment by zernonia** [comment]
and why revert those changes for landing page ya? Particular to logo and config stuff? Did you not like it? 😅

**Comment by khairulhaaziq** [comment]
> @khairulhaaziq Why do we merged [this](https://github.com/radix-vue/radix-vue/pull/175/commits/f09b671bf1055637a5ccded1d2bd234bb13eb7f0) ya? This messed up more responsive ui

wait what did I change? I thought the merge fixed something and then when I merged it broke everything and then I revert to your last merge

**Comment by khairulhaaziq** [comment]
> and why revert those changes for landing page ya? Particular to logo and config stuff? Did you not like it? 😅

oww shoot the logo is gone. I wanted to revert to your latest commit. not sure whats going on, will check

**Comment by khairulhaaziq** [comment]
> and why revert those changes for landing page ya? Particular to logo and config stuff? Did you not like it? 😅

I reverted to your last push. now the logo is showing on [preview](https://8e94e4b2.radix-vue.pages.dev/) but not in the [final build](https://www.radix-vue.com/) . Do you know the reason?

**Pull request merged**
