### PR TITLE
feat(Collapsible): add disableAnimation to block animation

### PR DESCRIPTION
**Pull request by kaishuige**
feat: #920

### CODE REVIEW

**Comment by kaishuige** [comment]
#920

**Comment by zernonia** [comment]
Thanks for the PR @kaishuige , but I don't see the benefit for adding `disableAnimation` props. The user can disable animation by using `class` binding based on condition as well. 

```html
  :class="{ 'animate-open': !isDragging  }"
```

**Comment by kaishuige** [comment]
I'm the one who missed the class attribute.

**Comment by kaishuige** [comment]
> Thanks for the PR @kaishuige , but I don't see the benefit for adding `disableAnimation` props. The user can disable animation by using `class` binding based on condition as well.
> 
> ```
>   :class="{ 'animate-open': !isDragging  }"
> ```

The disableAnimation parameter can be resolved #920, The class attribute doesn't seem to work.

**Pull request closed without merging**
