### PR TITLE
Docs(AlertDialog): Fix default values for the components

### PR DESCRIPTION
**Pull request by dwightjack**
Correct the documentation about the default values for some of the components in `AlertDialog`.

### CODE REVIEW

**Comment by zernonia** [comment]
the `meta/*.md` files were auto-generated. I think `vue-component-meta` couldn't pick up the default props from `Dialog` in this case. We should assign a default `as` in the `AlertDialog` component instead.

**Comment by dwightjack** [comment]
Oh, sorry, I didn't noticed it. I'll try to investigate if we can fix this issue via vue-component-meta.

**Comment by dwightjack** [comment]
@zernonia I investigated this problem, and indeed, `vue-component-meta` is not picking the default value, probably because it's not defined in the derived components (for example `AlertDialogAction`), but in the parent component (`DialogClose`). 

I am not familiar with `vue-component-meta` but I don't think it could infer the default value in any way. One option could be to re-define the default values in the derived components, even if that's a repetition 🤔 .

**Comment by zernonia** [comment]
Yup. The `vue-component-meta` is using static analysis, there's some limitation to it. I'm ok with re-defining the default value for them 😁

**Comment by dwightjack** [comment]
Cool. I will update the PR 👍

**Comment by dwightjack** [comment]
@zernonia sorry for the delay. I updated the PR.

**Review by zernonia — APPROVED** [review]
LGTM! Thanks for the PR @dwightjack ! 🚀

**Pull request merged**
