### PR TITLE
Refactor `useSingleOrMultiple`

### PR DESCRIPTION
**Pull request by onmax**
# What does it fix?

Sets the `type` prop automatically inferring the value from `v-model` or `defaultValue`. 

For example:

```html
<script setup lang="ts">
const str = ref('my-item')
</script>

<template>
<AccordionRoot v-model="str" /> <!-- `type` is single. If you use add `:type=multiple`, TS won't like it
</template>
```

This improves DX making easier to use.

I also take the oppportunity to create a new `SingleOrMultipleProps` which is the set of props that are used in `Accordion` and `RadioGroup`, making a unique codebase for both.

## Screen captures

This is an example of what the user will see:

| Type | DX |
|--------|--------|
| Setting the type as `single`| image|
| Setting the type as `multiple`| image| 

# Deprecated `Type`

I think the type `Type` is too broad and might create confusion. I checked the whole project, and it seems that this type is only used in the `Accordion` and `GroupRadio`. I think is better to be explicit in this case.

I marked as `@deprecated`, in the next major release, it could be removed.

## Solves #633

# TODO

- [ ] Update the docs removing the `required` prop (?). Not sure if this is the right thing. The `type` props is still required if `v-model` and `defaultValue` are not being used

### CODE REVIEW

**Comment by onmax** [comment]
Any feedback is welcomed 😃

**Comment by onmax** [comment]
I am using `generic` from Vue. Not sure if this will cause a problem, since it is a feature introduced in Vue 3.3:

https://github.com/radix-vue/radix-vue/pull/693/files#diff-3a4dd1dcd0ec33556b17ff15436567d35d42e4c602e47df80af5a3b915522a8bR61

**Review by zernonia — COMMENTED** [review]
Once again nicely done @onmax ! will onhold this for 2.0 as it has refactoring and deprecation. 😁

At the mean time can you help update the JSDOC for `modelValue` and `defaultValue` so that it would cater for all 3 `AccordionRoot`, `ToggleGroupRoot`, `ToolbarToogleGroup`?

**Comment by onmax** [comment]
> Once again nicely done @onmax ! will onhold this for 2.0 as it has refactoring and deprecation. 😁

But we could mark it as `@deprecated` in the `1.5.0` version? Then in `2.0.0`, we could remove it?

**Comment by onmax** [comment]
> At the mean time can you help update the JSDOC for modelValue and defaultValue so that it would cater for all 3 AccordionRoot, ToggleGroupRoot, ToolbarToogleGroup?

I pushed #a910fce with new comments. I am having issues when I try to run `pnpm run build`, so I cannot preview the documentation page. 

Is there anything else missing to do?

**Pull request merged**
