### PR TITLE
fix: slot prevents out transition for non-modal dropdown and select components

### PR DESCRIPTION
**Pull request by MellKam**
resolves: #800 

The main change that brought the out transition back was:

```ts
if (childrens.length === 1)
	return cloned
```

Basically unwrap the vnodes array if it only has one element. Idk why this is fixed, but it works XD. I'd like others to look at this, because I'm not really sure about it. 

I should probably write a story to showcase this, but I'm lazy right now. I'll get back to it tomorrow.

### CODE REVIEW

**Comment by zernonia** [comment]
Tested out and indeed was the array of vnodes causing the out animation to be missing.
Thanks for the fix and improvement here @MellKam !  That's a brilliant solution! 💚

Not sure what kind of story can we write here, and writing test for animation/transition part is still something I need to figure out lol 😂

**Review by zernonia — APPROVED** [review]

**Comment by MellKam** [comment]
I updated the DropdownMenu story with out animation using `tailwindcss-animate` plugin. 

https://github.com/radix-vue/radix-vue/assets/51422045/15e84819-b60a-4514-af7a-f2f3c561fd6a

I have also tried to come up with some test that would check that animation is going as it should, but no success.

**Comment by MellKam** [comment]
@zernonia Why do we have the `require` in the tailwind configs? Is this necessary? If not, I would like to open the separate PR and update all configs to esm only.

**Comment by zernonia** [comment]
Nice @MellKam ! I thought of adding the `tailwind-animate` plugin to histoire too!
We can change `tailwind.config` to `esm` version 😁

**Pull request merged**
