### PR TITLE
feat: add nuxt module

### LINKED ISSUE #123: feat: Add Nuxt module for Component autoImport
We should have a module that would autoImport all component in `radix-vue`.

### PR DESCRIPTION
**Pull request by owlnai**
This PR adds a Nuxt module for auto-imports. The Nuxt playground is updated too to make use of this module.

## Description
- This adds a Nuxt module built with unbuild as a package to be released alongside `radix-vue`. 
- Every exported component by `radix-vue` will be consumed by the Nuxt autoimports - no need to keep a separate list ✨ 
- Updated the Nuxt playground to avoid explicitly importing Radix components and Vue `ref`.
## Related Issue
Resolves #123 

## How Has This Been Tested?
Tested the Nuxt playground and all primitives that were present work out-of-the-box, no import needed. 

## Screenshots (if appropriate):
Screenshot from Nuxt Devtools showing components auto-imported by the library

### CODE REVIEW

**Comment by zernonia** [comment]
Awesome job @owlnai!!!

@khairulhaaziq  How do you think we should release this package ya? As another package `@radix-vue/nuxt`, or we bundle all together into `radix-vue`, and access Nuxt module from `radix-vue/nuxt`, similar to [Unocss](https://unocss.dev/integrations/nuxt)

**Comment by khairulhaaziq** [comment]
> Awesome job @owlnai!!!
> 
> 
> 
> @khairulhaaziq  How do you think we should release this package ya? As another package `@radix-vue/nuxt`, or we bundle all together into `radix-vue`, and access Nuxt module from `radix-vue/nuxt`, similar to [Unocss](https://unocss.dev/integrations/nuxt)

Bundling together seems like a decent approach, what do you think?

**Comment by zernonia** [comment]
> Bundling together seems like a decent approach, what do you think?

I think so too. Main benefit I see is that doing so Nuxt will always be up-to-date with the latest version of Radix-vue. And given that we have tree-shakeable capacitbility, need not to worry to much about the bundled size 😁

**Comment by owlnai** [comment]
I agree that since the package is reasonably light (<1kb _if_ bundled) we could ship it with the core package. However, the downside of bundling together is that we wouldn't be able to fix Nuxt issues without bumping the core package

**Comment by zernonia** [comment]
> I agree that since the package is reasonably light (<1kb _if_ bundled) we could ship it with the core package. However, the downside of bundling together is that we wouldn't be able to fix Nuxt issues without bumping the core package

I believe that should be fine. As we may not encountered many issue with the Nuxt package. 😁
Could you help update the `build`  function to include nuxt module into core?

**Comment by owlnai** [comment]
> As we may not encountered many issue with the Nuxt package. 😁

True. Also, SSR issues will be easier to fix since we can now make adjustments to Nuxt itself 😄 
> Could you help update the build function to include nuxt module into core?

The build command already builds all /packages/ so that should be covered. I have included the Nuxt export so `radix-vue/nuxt` should work, in theory, as a bundled package. I've never used multiple exports so I'd be glad if someone else could review it :)

**Comment by zernonia** [comment]
can we build `nuxt` into `radix-vue/dist/nuxt`, and change the import path from `"./../radix-nuxt/dist/index.mjs"` to `./dist/nuxt/index.mjs` ?

reason is `npm publish` will look at the `files` in `package.json`.. using relative path might messed up the pathing I afraid.
```json
 "files": [
    "./dist",
    "./LICENSE"
  ],
```

**Comment by owlnai** [comment]
Right, good catch. Unbuild now outputs to the radix-vue/dist directory.
```
i Building @radix-vue/nuxt                                                          16:51:10
√ Build succeeded for nuxt                                                          16:51:13
  ../radix-vue/dist/nuxt/index.cjs (size: 753 B, exports: default)                  16:51:13
  ../radix-vue/dist/nuxt/index.mjs (size: 475 B, exports: default)  
```

**Comment by zernonia** [comment]
Really a job well done @owlnai !!! Appreciate the contributions! 😁❤️

**Pull request merged**
