### PR TITLE
feat: add Primitive component, with asChild utility

### PR DESCRIPTION
**Pull request by zernonia**
## Description

Implement `asChild` props similar to Radix UI (by using a custom wrapped component, namely `Primitive`.)
Inspired by [Ark UI]() approaches, but instead of using `jsx`, we implemented a `vue-sfc` approach.

## Related Issue
#70 

 
## How Has This Been Tested?
Updated the demo on `CollapsibleDemo`. You could inspect the element via browser devtools to see that there's only 1 button element.

## Screenshots (if appropriate):

image

### CODE REVIEW

**Review by khairulhaaziq — CHANGES_REQUESTED** [review]
Simply genius! Looks good! however I think we should refrain from using the namescaped naming, is it necessary, also I think we should find a better name, maybe AsChildWrapper? if you think we should discuss the name further lets do on discord

**Comment by zernonia** [comment]
@khairulhaaziq  I've changed from using namespaced, to individual component. 
I think naming `Primitive` will help other dev to understand that it serves the same purpose as the "Primitive" component in Radix UI

**Comment by khairulhaaziq** [comment]
> @khairulhaaziq I've changed from using namespaced, to individual component. I think naming `Primitive` will help other dev to understand that it serves the same purpose as the "Primitive" component in Radix UI

cant the html/tag element be inferred from the slots? meaning the Primitive is dynamic, inferred from the child. is that possible?

**Comment by zernonia** [comment]
> Edit: Ah sorry I just take my time on it, so the PrimitiveButton only defaults to button, and if the asChild attribute is added, it resolve to the child element of any tag, correct?

Yup. How it works is that by default it will render a `button` (using PrimitiveButton). But if we pass `asChild` props, it will render whatever child tag

**Review by khairulhaaziq — APPROVED** [review]
lgtm!

**Pull request merged**
