### PR TITLE
(WIP) feat: add Renovate

### LINKED ISSUE #998: [Feature]: Integrate Renovate/Dependabot
### Describe the feature

Would it be beneficial to integrate something like [Renovate](https://github.com/apps/renovate) or [Dependabot](https://github.com/dependabot) to help keeping our dependencies up to date?

I can look into integrating one of these if it would be helpful for us.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

### PR DESCRIPTION
**Pull request by epr3**
Closes #998.

### CODE REVIEW

**Comment by zernonia** [comment]
I've enabled the Renovate GitHub App 😁

**Comment by epr3** [comment]
Now, hopefully, a PR like this will be opened: https://docs.renovatebot.com/getting-started/installing-onboarding/#repository-onboarding

**Comment by zernonia** [comment]
Changed it to `Mode: Interactive`. Also we don't need the changes in this PR right?

**Comment by zernonia** [comment]
@epr3  should be good now https://github.com/radix-vue/radix-vue/pull/1049

**Comment by epr3** [comment]
> Changed it to `Mode: Interactive`. Also we don't need the changes in this PR right?

@zernonia Yes, I'll close this PR. Thank you for changing the setting! 🚀

**Pull request closed without merging**
