### PR TITLE
[refactor]: popper related components

### PR DESCRIPTION
**Pull request by zernonia**
Changed all popper related component to use Popper primitive.

List of components to refactor to use Popper:
- [x] Dropdown Menu
- [x] Context Menu
- [x] HoverCard
- [x] Popover
- [x] Tooltip

### CODE REVIEW

**Comment by khairulhaaziq** [comment]
I think this pr should also fix contextmenu to reuse most of dropdownmenu and make submenu works with it. there are several build errors currently, and popover collision-aware not working

**Review by khairulhaaziq — COMMENTED** [review]
I think we can safely rewrite the whole contextmenu to use the dropdown menu, with the trigger being the only thing that needs to change, other than that there are issues with building the package

**Comment by zernonia** [comment]
> I think we can safely rewrite the whole contextmenu to use the dropdown menu, with the trigger being the only thing that needs to change, other than that there are issues with building the package

Im thinking of making that rewrite in another MR

**Comment by khairulhaaziq** [comment]
> > I think we can safely rewrite the whole contextmenu to use the dropdown menu, with the trigger being the only thing that needs to change, other than that there are issues with building the package
> 
> Im thinking of making that rewrite in another MR

yeah okay fair. I think fix the build and we're okay to merge. should we set avoidCollisions default to true in PopperContent itself?

**Comment by zernonia** [comment]
> and popover collision-aware not working

hmm.. the `avoidCollitions` was `true`, and it seems fine tho? 🤔

image

**Comment by khairulhaaziq** [comment]
> > and popover collision-aware not working
> 
> hmm.. the `avoidCollitions` was `true`, and it seems fine tho? 🤔
> 
> image

yeah no I fixed that https://github.com/radix-vue/radix-vue/pull/160/commits/8b4472eb62ded5f345eb503ac39a323a7da28c55

**Review by khairulhaaziq — APPROVED** [review]
lgtm 🚀

**Comment by zernonia** [comment]
> > > I think we can safely rewrite the whole contextmenu to use the dropdown menu, with the trigger being the only thing that needs to change, other than that there are issues with building the package
> > 
> > 
> > Im thinking of making that rewrite in another MR
> 
> yeah okay fair. I think fix the build and we're okay to merge. should we set avoidCollisions default to true in PopperContent itself?

Yeah the build was fixed. hhmm.. seems like `avoidCollisions` is true by default in PopperContent. Maybe there's some props merging conflict using `v-bind="props"`.

**Pull request merged**
