### PR TITLE
fix: don't set disabled attribute to `MenuItem` component

### PR DESCRIPTION
**Pull request by MellKam**
resolves: #600

Original radix-ui doesn't set disabled attribute to MenuItem component. Only `aria-disabled` and `data-disabled` https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/menu/src/Menu.tsx#L708-L709

If you want to use MenuItem as button - use `asChild` props 

```vue
<MenuItem as-child disabled>
	<button disabled>
		Hello world
	</button>
</MenuItem>
```

### CODE REVIEW

**Comment by sadeghbarati** [comment]
But `MenuItemImpl` has `disabled` prop which you are removing it 🙅 

https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/menu/src/Menu.tsx#L639

---

We have to investigate why Vue act like this, it should act like this 👇 

`isDisabled: true` -> disabled attributes appears

`isDisabled: false` or `undefined` ---> disabled attribute should remove completely

[`Vue SFC Playground`](https://play.vuejs.org/#eNp9UUtPAyEQ/isjFzVp2kNvzdb46kEParRHLlt2dqVlAWFomzT73wXWvhLThAMz34NvmB17sHa4DsgmrPDCSUvgkYK941q21jiCHTisoYPamRauI/Waa66F0Z5A+mfpy4XCCqaJdlOXyuMt18WoN4s2sSBsrSoJYwVQLAKR0TCp/qRTzo4+nGUSwM8G48mCUa/IXkf9vVBSrM7EMcTVmdXcNI3CE4NidJKFDRj5OEgtm+HSGx3/YJde4EyY1kqF7t2SjINyNoGMJKxUymxec49cwMG+L75RrP7pL/029Tj7cOjRrZGzA0ala5B6ePb1htt4P4CtqYKK7AvgJ3qjQsrY0x6DrmLsE15O+5I3KXUz97Mtofb7oVLQxOwyn7O43acLox/jjofjrOO6Y90vO53C/A==)

**Comment by sadeghbarati** [comment]
I think we should add `withDefault` to the MenuItemImpl `defineProps`

https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Menu/MenuItemImpl.vue#L19


```ts
const props = withDefaults(defineProps<MenuItemImplProps>(), {
   disabled: false
})
```

**Comment by sadeghbarati** [comment]
@MellKam I'm checking Radix UI, you are right

- MenuItem -> should have disabled prop

- MenuItemImpl -> disabled attribute must be removed

**Comment by MellKam** [comment]
> @MellKam I'm checking Radix UI, you are right
> 
> * MenuItem -> should have disabled prop
> * MenuItemImpl -> disabled attribute must be removed

Yep, it's a bit weird at first, but If you think about radix more as the set of logic that can be used on other components, it makes sense. We shouldn't use element specific attributes. It's just confusing that it calls "disabled" but doesn't actually set disabled on the element. 

```vue
                   ↓ handle logic for disabled menu item
<MenuItem as-child disabled>
            ↓ set disabled attribute
    <button disabled>  
        Hello world
    </button>
</MenuItem>
```

**Pull request merged**
