### PR TITLE
chore: fix lint issues

### PR DESCRIPTION
**Pull request by onmax**
It would be nice to have custom rules in the `eslint.config.cjs` for the files `**/**.*.story.vue` and turn off rules like `no-console` and `no-alert`, but I am not sure how to implement it.

So, instead I am using `// disable-next-line no-console` in multiple stories

### CODE REVIEW

**Comment by zernonia** [comment]
we purposely exclude linting `story` files because we wanna keep some code for easier debugging. We don't really need to add those `// eslint-disable-next-line no-alert` too as it's just dev environment.

**Review by zernonia — CHANGES_REQUESTED** [review]
we purposely exclude linting `story` files because we wanna keep some code for easier debugging. We don't really need to add those `// eslint-disable-next-line no-alert` too as it's just dev environment. 

Let's revert that ya 😁

**Comment by onmax** [comment]
Perfect. I've added some eslint rules to ignore stories.

Can I create another PR updating eslint to v9 and flat config? I will try the changes to the minimum

**Comment by zernonia** [comment]
Awesome!!!
Let's create another PR for v9. I heard some bad experience with v9 🙈

**Pull request merged**
