### PR TITLE
added codemods to docs

### PR DESCRIPTION
**Pull request by dfordp**
To assist with the upgrade from radix-vue to reka-ui, we have added features that utilize codemods to automatically update your code to many of the new updates and patterns. 

These codemods include breaking changes which aren't implemented interally but have to updated across multiple repositories using the framework.

These will run the following codemods from the radix-vue Codemod repository:

- **Remove filter-function props**
- **Rename controlled state to v-model**
- **Remove deprecated step prop**

#### Remove filter-function props 
 Combobox has been refactored and improve to support better custom filtering. 
  - Additional Details
    - Replace searchTerm props of Root to Input's v-model
    - https://go.codemod.com/3lqPTdS
#### Rename controlled state to v-model
   Replace v-model:checked, v-model:pressed with more familiar API for form component.
   - Additional Details
    - Reposition VisuallyHidden - Previously VisuallyHidden were position at the root node, causing style scoped to not be applied.
     - https://go.codemod.com/TkPrj5g
#### Remove deprecated step prop 
    Use prevPage/nextPage props for greater control.
    - Additional Details
      - https://go.codemod.com/w0lCajc

### CODE REVIEW

**Comment by zernonia** [comment]
@dfordp  Amazing work!!!! Is there a way to just run one codemods to apply all changes at once?

**Comment by dfordp** [comment]
@zernonia I can create a migration recipe which can install all the codemods at once 

I will complete by EOD

**Comment by dfordp** [comment]
@zernonia sir it's done

Added migration recipe codemod which would run add all the respective codemods at once

**Comment by zernonia** [comment]
Awesome!!! Exciting! 🚀 
Thank you so much for working on these codemods.. I shall give it a try soon!

Also, how about the data-attributes and css naming changes from `radix` to `reka`? Is that achievable? 😁

**Comment by dfordp** [comment]
@zernonia sir yeah it's possible 

I didn't see any in the migration guide that's I didn't add those yet.

**Comment by zernonia** [comment]
It's here yaa https://reka-ui.com/docs/guides/migration#import-statement-changes and https://reka-ui.com/docs/guides/migration#import-statement-changes

**Comment by dfordp** [comment]
@zernonia sir I have added the said changes and also added those changes to the migrate recipe

**Review by zernonia — APPROVED** [review]
Awesome! I see all the breaking changes migration has been done. I'll merge this in ya! Will test them out soon!
You rock @dfordp !!! 🚀🔥

**Pull request merged**
