### PR TITLE
fix: export toast utils types

### PR DESCRIPTION
**Pull request by hrubysi**
Closes https://github.com/radix-vue/radix-vue/issues/960

### CODE REVIEW

**Comment by zernonia** [comment]
I'm good with the solution, however I think the problem would exist for other components too. Can you help check if `library` mode with Dialog component also face the similar issue? 😁

**Comment by hrubysi** [comment]
That's a good point, DialogContentProps have the same issue. 
The only solution I know of is adding export statement of utils to each component index, but I don't even know why that helps. I would expect it to work without it.

**Comment by zernonia** [comment]
@hrubysi  I realized it might be some `tsconfig` issue on your end. I've forked your stackblitz and modified the `tsconfig` and it bundles correctly (without type issue)

https://stackblitz.com/edit/vitejs-vite-hc6og5?file=tsconfig.lib.json

**Comment by hrubysi** [comment]
You are right. I didn't realize, that base vue ts config doesn't include baseUrl, which is why it didn't work.
Thank you, I'm closing this.

**Pull request closed without merging**
