### PR TITLE
Feat: Accordion

### PR DESCRIPTION
**Pull request by mujahidfa**
#1

### CODE REVIEW

**Comment by khairulhaaziq** [comment]
lgtm, for phase 1 its ok

**Review by khairulhaaziq — APPROVED** [review]

**Comment by mujahidfa** [comment]
Eh jap belum setel lagi, ada bugs lagi haha

**Comment by khairulhaaziq** [comment]
> Eh jap belum setel lagi, ada bugs lagi haha

sebenarnya kalau nak add arrow navigation senang je, pakai shared useArrowNavigation , tengok contoh dekat radio group usage, add for every component yg nak difokus `data-radix-vue-collection-item`

**Comment by mujahidfa** [comment]
Oh actually bukan arrow navigation je, aku tengah nak cari a good way to support single collapse.

**Comment by mujahidfa** [comment]
Todo's:
- [ ] useId hook for `triggerId`
- [ ] arrow navigation

**Review by khairulhaaziq — COMMENTED** [review]
sebenarnya saya rasa ni masih tak fungsi with v-model, it might can return the new value to v-model, tapi it is still not controllable, meaning kalau try create a button that change the ref value, collapsible isnt reactive to that. I also dont know yet how to make it work

**Comment by khairulhaaziq** [comment]
> sebenarnya saya rasa ni masih tak fungsi with v-model, it might can return the new value to v-model, tapi it is still not controllable, meaning kalau try create a button that change the ref value, collapsible isnt reactive to that. I also dont know yet how to make it work

fixed: https://github.com/radix-vue/radix-vue/pull/90 
boleh tengok cara aku fix, dekat demo ada tambah button which modify ref value to show how it is controllable, and it works if v-model is removed aswell.

**Pull request merged**
