### PR TITLE
feat: expose highlighted/selectedValue in combobox root

### PR DESCRIPTION
**Pull request by HuakunShen**

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks for the PR @HuakunShen . We can merge this feature in, but will be deprecated in `v2`. 😁

**Comment by HuakunShen** [comment]
@zernonia Thanks, I just need to use it now.

**Comment by zernonia** [comment]
Yup. There will be `@highlight` event which has the value and html for the current highlighted value. Similar to https://www.radix-vue.com/components/listbox.html#root

**Comment by HuakunShen** [comment]
@zernonia Done

**Pull request merged**
