### PR TITLE
feat(navigation-menu): multiple triggers on navigation menu

### LINKED ISSUE #565: [Feature]: Navigation Menu only trigger when "clicked"
### Describe the feature

Allow the [navigation menu component](https://www.radix-vue.com/components/navigation-menu) to be triggered on click

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

### PR DESCRIPTION
**Pull request by Chrtyaka**
Hi 👋🏻 Closes #565 

### NavigationMenuRoot.vue
- add props `openOnClick`, `openOnHover`

Both props a optional, and `true` by default. It's not a breaking change.

Actually, I had 3 solutions in my mind:
1. Create prop `triggers` which can be array of strings, i.e `['hover', 'click']`. But it's too complicated. 
2. Create props trigger, with values `click` or `hover` like [element-plus popover](https://element-plus.org/en-US/component/popover.html#attributes).  But it's not flexible. We can use only one trigger at the time. It would be a breaking change
3. Create two props for disable hover o click. I choose this one 😄 Thanks to [vuetify](https://vuetifyjs.com/en/api/v-menu/#links)

### Tests
add test for both props. Includes trigger on hover
### Docs
update docs for both props

### Default

https://github.com/radix-vue/radix-vue/assets/20302368/c04c207e-7d94-4ee2-9bb6-3b5964a12392

### openOnHover -- open only by hover

https://github.com/radix-vue/radix-vue/assets/20302368/34a63919-761e-49af-be5a-144624d7d5dd

### openOnClick -- open only by click

https://github.com/radix-vue/radix-vue/assets/20302368/069a546f-580c-44cd-9c4a-3296b0e31bff

### CODE REVIEW

**Comment by zernonia** [comment]
Yoo @Chrtyaka ! Thanks for the PR!!!

May I ask why the first solution is complicated ya? I kinda prefer that tho 😂

**Comment by Chrtyaka** [comment]
Yeah, at first I wrote solution with arrays. But I looked in the code, and I didn't like it 😅 

It's just my personal experience. Two boolean props are easier for me to operate than an array. 
But if you think that array is the better solution, I can rewrite it. 

No problem👍🏻

**Comment by Chrtyaka** [comment]
Yes, this is a good point. I think something like `disableClickTrigger` or `disableHoverTrigger` would work.

Because `disableOpenOnClick` and `disableOpenOnHover` are too many symbols 😅

Would that be okay?

**Comment by zernonia** [comment]
That sounds perfect! 🤩

**Comment by Chrtyaka** [comment]
Done!

Props names changed, disabled by default

**Comment by zernonia** [comment]
Nicely done @Chrtyaka ! I've update the `disableClickTrigger` abit to make sure we only disable based on `pointerType: 'mouse'`. We want to make sure accessibility for the component 😁

**Comment by yoni-noma** [comment]
It this going to work on the react version as well? :)

**Pull request merged**
