### PR TITLE
feat(RadioGroupIndicator): add forceMount props

### PR DESCRIPTION
**Pull request by zernonia**

### CODE REVIEW

**Comment by DamianGlowala** [comment]
Noticed the following in checkbox'es indicator: https://github.com/radix-vue/radix-vue/blob/03cdc60f5721646fb60ed8adb48fc676ed2bb2cc/packages/radix-vue/src/Checkbox/CheckboxIndicator.vue#L39

Is it relevant or unrelated to this PR?

**Comment by zernonia** [comment]
> Noticed the following in checkbox'es indicator:
> 
> https://github.com/radix-vue/radix-vue/blob/03cdc60f5721646fb60ed8adb48fc676ed2bb2cc/packages/radix-vue/src/Checkbox/CheckboxIndicator.vue#L39
> 
> Is it relevant or unrelated to this PR?

Thanks @DamianGlowala ! It make sense!

**Comment by DamianGlowala** [comment]
I should have also mentioned the following difference which might be relevant:
https://github.com/radix-vue/radix-vue/blob/03cdc60f5721646fb60ed8adb48fc676ed2bb2cc/packages/radix-vue/src/Checkbox/CheckboxIndicator.vue#L36

Thank you for adding this prop! ❤️

**Comment by zernonia** [comment]
hmm.. not sure.. I've leaving it out as Radix UI doesn't have that style. 😁

**Pull request merged**
