### PR TITLE
refactor: createContext, crateCollection and more

### PR DESCRIPTION
**Pull request by MellKam**
The main thing that was done was to rewrite the "provide/inject" to the `createContext` composable. In addition, a few minor changes were made to improve typings and reusability.

1. Removed `/shared/component` folder and moved content to the `/src`.
2. Rewritten `useCollection` composable with internal use of `createContext`.
3. Improved typings for `useStateMachine` composable
5. Handle case with object emits in `useEmitAsProps`
6. Removed duplicate types `Orientation` and `Direction`, now they are only taken from the `@/shared/types` file.

Good luck in reviewing all of this 😄.

### CODE REVIEW

**Comment by MellKam** [comment]
I complete the rewrite to `createContext` composable for all components. Check it out @zernonia

**Comment by zernonia** [comment]
Thanks @MellKam ! I will look at this PR when I have more free time yaa.. as it involves all the component, and need to go through the code thoroughly 😁

**Comment by zernonia** [comment]
Hey hey @MellKam ! Sorry for delaying this PR.. as part of v1.. I would love to have this feature merge in! Could you resolve these conflicts, and change the target branch to `v1`? 😁

**Comment by MellKam** [comment]
> Hey hey @MellKam ! Sorry for delaying this PR.. as part of v1.. I would love to have this feature merge in! Could you resolve these conflicts, refactor new component (Toast, Pagination, Combobox) and change the target branch to `v1` please? 😁
> 
> Appreciate it!

Sure, I'll do it.

**Pull request closed without merging**
