### PR TITLE
Tabs

### PR DESCRIPTION
**Pull request by onmax**
Implemented `Tabs` components

## Description
Using the [Radix API](https://www.radix-ui.com/docs/primitives/components/tabs#content)

## Related Issue
See #145 

## Motivation and Context

Someone has to do it duh

## How Has This Been Tested?
Just the playground and multiple demos using this component

### CODE REVIEW

**Comment by onmax** [comment]
I have implemented all the props/events that are described [here](https://www.radix-ui.com/docs/primitives/components/tabs) except for the `forceMount` in the `TabContent`.

I think that prop has to do something with React and therefore nothing to do in Vue?

**Comment by khairulhaaziq** [comment]
there are some issues:
- [ ] When activation mode is manual, it works as expected where only when clicked the tabs are changed, however focus/active style arent showing
- [ ] On vertical navigation, need to preventDefault so it doesnt scroll. I think on horizontal need to add that aswell

Other than that, I think it's perfect!

**Review by khairulhaaziq — COMMENTED** [review]
there are some issues:
- [ ] When activation mode is manual, it works as expected where only when clicked the tabs are changed, however focus/active style arent showing
- [ ] On vertical navigation, need to preventDefault so it doesnt scroll. I think on horizontal need to add that aswell

Other than that, I think it's perfect!
p/s: update the readme table for tabs when you're done!

**Comment by onmax** [comment]
Don't merge yet. I just realised that it might be important to add `onValueChange` event. I completely forgot 🤦

**Comment by khairulhaaziq** [comment]
> Don't merge yet. I just realised that it might be important to add `onValueChange` event. I completely forgot 🤦.
> 
> Or maybe we don't want it, since user can access a similar event?

no need. we're using v-model, so every props of value + onValueChange is replaced by a single v-model value

**Pull request merged**
