### PR TITLE
[Popover]feat: 2/3(Complete API)

### PR DESCRIPTION
**Pull request by onmax**
## Screenshots (if appropriate):

# TODO
- If we have a stack of dialogs, one on top of other, we have to make sure to handle events correctly and no trigger all of them at same time

### CODE REVIEW

**Comment by onmax** [comment]
Sorry @zernonia for bothering.

I am updating the `Popover` with the `DismissableLayer` and the `FocusScope`.

But I am getting the following error in the a31e9b8 commit

image

I would appreciate a help on this. I am trying to follow the code from `Menu` but I didn't see where the error is.

**Comment by zernonia** [comment]
> Sorry @zernonia for bothering.
> 
> I am updating the `Popover` with the `DismissableLayer` and the `FocusScope`.
> 
> But I am getting the following error in the [4df79d0](https://github.com/radix-vue/radix-vue/commit/4df79d05afbd2d3e65ec6e74be903c5776ff8645) commit
> 
> image
> 
> I would appreciate a help on this. I am trying to follow the code from `Menu` but I didn't see where the error is.

Hey @onmax .. I've commented here yaa.. But not sure if that's the cause...

**Comment by onmax** [comment]
@zernonia I feel overwhelmed. I have a lot of work to do for my job atm.

I tried to finish this component, but I am lost. I need time to focus and understand the new changes like `DismissableLayer` and `FocusScope`.

Before having those components, I was implementing the `Popover` with composables rather than renderless components.

With this change of paradigm, I need to rethink how to implement for example the `disabled` flag for the `Popover` and I have no idea where to start. I have to make multiple changes like that, and I basically don't have the time.

So please, feel free to take over so we can mark this feature as done. Otherwise, I will be working on `Radix Vue` in 10 days or so. 😄 

Thanks

**Comment by zernonia** [comment]
Thanks for the PR @onmax . I've created another PR (https://github.com/radix-vue/radix-vue/pull/312), and ported some of your code there.. I will close this PR for further reference for some composables that you've created 😁

**Pull request closed without merging**
