### PR TITLE
dev: refactor and create a shared useVModel util

### PR DESCRIPTION
**Pull request by khairulhaaziq**

### CODE REVIEW

**Comment by zernonia** [comment]
did a quick test with useVModel from `vueuse`, the size comparison (before/after), increase around `800b`. And the imlpementation for this is easy, due to the `defaultValue` props.

Screenshot 2023-06-28 at 4 05 40 PM

image

**Comment by zernonia** [comment]
Given that we dont need to manually handle these (well-written, well-tested) composable, I would prefer `useVModel` from Vueuse 😁

**Comment by khairulhaaziq** [comment]
> Given that we dont need to manually handle these (well-written, well-tested) composable, I would prefer `useVModel` from Vueuse 😁

okay! I agree! create a PR!

**Comment by zernonia** [comment]
Hope you dont mind @khairulhaaziq .. I've pushed the vueuse dependencies, and updated the SwitchRoot  😬

**Comment by khairulhaaziq** [comment]
> Hope you dont mind @khairulhaaziq .. I've pushed the vueuse dependencies, and updated the SwitchRoot 😬

LGTM! Nice! once you approved I'll merge

**Review by zernonia — APPROVED** [review]

**Pull request merged**
