### PR TITLE
ci: add `pkg.pr.new` workflow

### PR DESCRIPTION
**Pull request by sadeghbarati**
Previously [#931](https://github.com/radix-vue/radix-vue/pull/931#issuecomment-2118886210)

https://github.com/stackblitz-labs/pkg.pr.new

### CODE REVIEW

**Review by zernonia — APPROVED** [review]

**Review by zernonia — APPROVED** [review]
Trigger approval again

**Comment by zernonia** [comment]
The pipeline is looking good! However running the `npm i xx` on stackblitz is throwing error the following error



 

image


Running locally has this error

image

cc @Aslemammad

**Comment by Aslemammad** [comment]
Oh that's bad news! https://pkg.pr.new/radix-vue/radix-vue@4a89b6b gives unmatching route! Let me try fixing.

Thank you for letting me know

**Comment by Aslemammad** [comment]
Let's hold this for a bit since the issue is upstream! Feel free to convert the PR to draft.

**Comment by Aslemammad** [comment]
we can try compact mode too! which works. But still, this has to be fixed and I'll try my best to deliver something soon.

**Comment by zernonia** [comment]
Thanks for your quick action @Aslemammad ! Yup will hold this PR for now 😁

**Comment by Aslemammad** [comment]
I appreciate that from you! 🙌

**Comment by Aslemammad** [comment]
I think after an approval, it should work now!

**Review by zernonia — APPROVED** [review]

**Comment by zernonia** [comment]
> I think after an approval, it should work now!

With `compact` flag indeed it works 😁

**Comment by zernonia** [comment]
LGTM! Merging this! 🚀

**Comment by Aslemammad** [comment]
Thank you so much @sadeghbarati & @zernonia for the huge support! ❤️

**Pull request merged**
