### PR TITLE
feat: allow hooking on Dialog animation end

### LINKED ISSUE #878: [Feature]: Emit event when Dialog's animation are completed
### Describe the feature

Hi, contributor of [@nuxt/ui](https://github.com/nuxt/ui) here. As we are porting features from v2 to v3, I noticed something I am unable to port when transitioning from HeadlessUI to Radix.

When using [modals programmatically](https://ui.nuxt.com/components/modal#control-programmatically), we listen to [`TransitionRoot @after-leave`](https://headlessui.com/react/transition#component-api) so we know we can reset the modal safely.

I understand that `Presence` is used under the hood, but I can't determine if I can use anything to hook into that.

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

### PR DESCRIPTION
**Pull request by noook**
Resolves #878 

Not sure this is the expected method, I'd love to have feedback on it

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks for the PR @noook . I'm thinking a more general solution for components that are using `Presence`. I did some test with dispatching custom event, and seems to work pretty well.

something like this 

```ts
  const dispatchCustomEvent = (name: 'enter' | 'after-enter' | 'leave' | 'after-leave') => {
    const customEvent = new CustomEvent(name, { bubbles: true, cancelable: true })
    node.value?.dispatchEvent(customEvent)
  }
```

Then in the `DialogIOverlay` (or any components with Presence) can add listener as such

```vue
<DialogOverlay class="animation" @leave="" @after-leave=""   />
```

**Comment by noook** [comment]
I get it, what do you think of it now @zernonia ?

I'm not sure all events can be fired, for example I haven't seen the `leave` event fired. Also, I am not sure I can detect `after-enter` either

**Comment by zernonia** [comment]
No prob @noook ! I've pushed some `dispatchCustomEvent` to cater for `after-X` event. 

I believe this feature fit your original request right? where you can hook into the animation state 😁

**Comment by noook** [comment]
That looks fine ! And yes, I tested in the stories it fits the request 🔥

**Comment by zernonia** [comment]
Right now it's not explicit that which component has the `hook`, but I'm planning to add them in docs soon 😁

**Comment by stevebauman** [comment]
I'm not seeing anywhere in the docs on how to do this? Was this removed in a later patch? I.e. this does not work (not events fired):

```vue
<DialogOverlay 
    @leave="onLeave"
    @after-leave="onLeave"
    v-on:leave="onLeave"
    v-on:after-leave="onLeave"
>...
```

Am I missing something?

**Pull request merged**
