### PR TITLE
[Checkbox] Step 2/3

### PR DESCRIPTION
**Pull request by DennisSmuda**
## Description

Step 2/3 for `Checkbox` component

## Related Issue

https://github.com/radix-vue/radix-vue/issues/135

### CODE REVIEW

**Comment by zernonia** [comment]
Hey hey @DennisSmuda ! Any update on this? 😁 It is ready for ready?

**Comment by DennisSmuda** [comment]
> Hey hey @DennisSmuda ! Any update on this? 😁 It is ready for ready?

Sorry @zernonia I was sick, I'll try and get to it this week 🤞

**Comment by zernonia** [comment]
@DennisSmuda  hope you are feeling good yaa 😁 Since `Checkbox` is almost done.. do you mind if I take over? 😁

**Comment by DennisSmuda** [comment]
@zernonia please do, I'm sorry I was too swamped these last couple days 🙏

**Comment by zernonia** [comment]
No problem @DennisSmuda ! Thanks for the PR ya! Closing in favor of https://github.com/radix-vue/radix-vue/pull/359

**Pull request closed without merging**
