### PR TITLE
refactor: use createContext composable for all components

### LINKED ISSUE #266: Throw error when missing injected value
I would like to propose to create some small utility to handle provided values. Because now there is no logic in components that would throw errors when injectedValue is missing. Here is an example of how radix handles this https://github.com/radix-ui/primitives/blob/main/packages/react/context/src/createContext.tsx . I think it's pretty easy to port to vue concepts.

### PR DESCRIPTION
**Pull request by MellKam**
It was easier for me to rewrite everything from scratch than to merge those conflicts in #371 XD. Also my mistake was trying to fit too many changes into one PR. So here I just changed provide/inject to createContext composable.

resolves #266

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks for the PR again @MellKam ! I should've look at it sooner 😂 Sorry for the trouble yaa

**Comment by zernonia** [comment]
working wonderfully!! Thanks @MellKam ! Can we include the changes for `Combobox` too? 😁

**Comment by MellKam** [comment]
> working wonderfully!! Thanks @MellKam ! Can we include the changes for `Combobox` too? 😁

Just forgot to push the commit

**Review by zernonia — APPROVED** [review]
LGTM!!

**Pull request merged**
