### PR TITLE
feat: OTP input

### PR DESCRIPTION
**Pull request by zernonia**

### CODE REVIEW

**Comment by sadeghbarati** [comment]
Thanks for the feature 🙏 

Note that one input that lookalike multiple input >>> multiple input

**Comment by zernonia** [comment]
Thanks @sadeghbarati !
what do you mean by "Note that one input that lookalike multiple input >>> multiple input" yaa? 😁

**Comment by sadeghbarati** [comment]
I shared a link in the OTP Input issue called "rci"

https://github.com/leonardodino/rci

The author of that repo finds a better way to create pin inputs instead of creating multiple inputs 

https://user-images.githubusercontent.com/8649362/136673700-bd227d9c-9919-49d6-ae92-bbbef7882365.png

**Comment by zernonia** [comment]
Ahh icic!! that's an awesome suggestion @sadeghbarati ! Yeah I would try out and see how extensible that approach is 🤩

**Comment by zernonia** [comment]
Saw this [Caveats](https://github.com/leonardodino/rci#caveats) from the package, which unfortunately limits the potential of creating different kind of OTP design. Thus I would like to stick with multi-input approach, which is much more flexible in terms of constructing custom design.

WDYT @sadeghbarati

**Comment by sadeghbarati** [comment]
Right ✅️ 

LGTM then ^_^

**Pull request merged**
