### PR TITLE
[AlertDialog] fix: remove the useScrollLock hook and toggle body pointer events instead

### PR DESCRIPTION
**Pull request by MellKam**
#273

### CODE REVIEW

**Review by khairulhaaziq — APPROVED** [review]

**Comment by khairulhaaziq** [comment]
so where's the scroll lock function? nvm Im reverting for now.

**Comment by MellKam** [comment]
Are you talking about this piece of code? 

```
watch(open, (open) => {
  if (open) {
    document.body.style.pointerEvents = "none";
  } else {
  	document.body.style.pointerEvents = null;
  }
})
```

I thought that we already have place to put it in AlertContent and I did so.

**Comment by khairulhaaziq** [comment]
> Are you talking about this piece of code?
> 
> ```
> watch(open, (open) => {
>   if (open) {
>     document.body.style.pointerEvents = "none";
>   } else {
>   	document.body.style.pointerEvents = null;
>   }
> })
> ```
> 
> I thought that we already have place to put it in AlertContent and I did so.

you understand we need to lock scroll for accessibility right?

**Comment by MellKam** [comment]
> you understand we need to lock scroll for accessibility right?

Oh, sorry, my bad. I just realized that pointer-events does not stop the scroll). Checked the radix sources and will try to reproduce it a bit later. They actally use different package to do this: "react-remove-scroll".

**Pull request closed without merging**
