### PR TITLE
fix: make switch controllable and unctrollable

### PR DESCRIPTION
**Pull request by khairulhaaziq**
make switch controllable via v-model or uncontrolled(works without v-model)
#22

### CODE REVIEW

**Comment by zernonia** [comment]
Could we introduce `@vueuse/core` into the dependencies? I think `useVModel` handle this case nicely.

**Comment by khairulhaaziq** [comment]
> Could we introduce `@vueuse/core` into the dependencies? I think `useVModel` handle this case nicely.

@zernonia we have thought and discussed about it, while we are only using small number of utilities, we think we better try to write/copy it than importing a huge dependency.

**Comment by zernonia** [comment]
Vueuse does have tree-shaking capabilities.. so I guess that should be fine right?
But yeah.. No problem with current approach. I just foresee that we might eventually need vueuse 😁

**Comment by khairulhaaziq** [comment]
> Vueuse does have tree-shaking capabilities.. so I guess that should be fine right? But yeah.. No problem with current approach. I just foresee that we might eventually need vueuse 😁

do you want to test and try adding it? see how much it effects the build size and the time to build? if not too much of difference we can consider it

**Pull request merged**
