### PR TITLE
feat: migrate to ESLint flat config

### PR DESCRIPTION
**Pull request by DamianGlowala**

### CODE REVIEW

**Comment by zernonia** [comment]
Thanks for the PR @DamianGlowala ! However it's throwing error when I run `pnpm lint:fix`


image

**Comment by DamianGlowala** [comment]
Thanks for the heads up, I'll look into this!

**Comment by DamianGlowala** [comment]
@zernonia just checked and it's working on my end. Have you installed dependencies and run `pnpm lint:fix` at the root of the repo?

**Comment by zernonia** [comment]
Yup. I've removed `pnpm-lock` and `node_modules` to make sure clean installation. But the problem still exists. Seems like there's something wrong with [Plugin renaming](https://github.com/antfu/eslint-config?tab=readme-ov-file#plugins-renaming) 😅 

Can you try clean installation too?

**Comment by DamianGlowala** [comment]
@zernonia could you please check it now? 😄

**Review by zernonia — APPROVED** [review]
Nice!! It works perfectly now @DamianGlowala !! Thanks for the effort and taking time to look into those problem 🙏🏻!

**Pull request merged**
