### PR TITLE
feat: implement aschild to relevant components

### PR DESCRIPTION
**Pull request by khairulhaaziq**
#93 

### #1 Accordion (Skip)
- [ ] Root
- [ ] Item
- [ ] Header
- [ ] Content

### #2 Alert Dialog
- [x] Trigger
- [x] Overlay
- [x] Content
- [x] Cancel
- [x] Title
- [x] Description

### #3 Aspect Ratio 
- [ ] Root

### #4 Avatar
- [x] Root
- [ ] Image
- [x] Fallback

### #5 Checkbox
- [x] Root
- [x] Indicator

### #6 Collapsible
- [x] Root
- [x] Trigger
- [x] Content

### #7 Context Menu (Skip)
- [x] Trigger
- [x] Content
- [x] Arrow
- [x] Item
- [x] Group
- [x] Label
- [x] CheckboxItem
- [x] RadioGroup
- [x] RadioItem
- [x] ItemIndicator
- [x] Separator
- [ ] Sub
- [ ] SubTrigger
- [ ] SubContent

### #8 DIalog
- [x] Trigger
- [x] Overlay
- [x] Content
- [x] Close
- [x] Title
- [x] Description

### #9 Dropdown Menu
- [x] Trigger
- [x] Content
- [x] Arrow
- [x] Item
- [x] Group
- [x] Label
- [x] CheckboxItem
- [x] RadioGroup
- [x] RadioItem
- [x] ItemIndicator
- [x] Separator
- [x] Sub
- [x] SubTrigger
- [x] SubContent

### #10 Form (Skip)
- [ ] Root
- [ ] Field
- [ ] Label
- [ ] Control
- [ ] Message
- [ ] Submit

### #11 Hover Card
- [x] Trigger
- [x] Content
- [x] Arrow

### #12 Label
- [x] Root

### #13 Menubar (Skip)
- [ ] Root
- [ ] Menu
- [ ] Trigger
- [ ] Content
- [ ] Arrow
- [ ] Item
- [ ] Group
- [ ] Label
- [ ] CheckboxItem
- [ ] RadioGroup
- [ ] RadioItem
- [ ] ItemIndicator
- [ ] Separator
- [ ] Sub
- [ ] SubTrigger
- [ ] SubContent

### #14 Navigation Menu (Skip)
- [ ] List
- [ ] Item
- [ ] Trigger
- [ ] Content
- [ ] Link
- [ ] Indicator
- [ ] Viewport

### #15 Popover
- [x] Trigger
- [ ] Anchor
- [x] Content
- [x] Arrow
- [x] Close

### #16 Progress
- [x] Root
- [x] Indicator

### #17 Radio Group
- [x] Root
- [x] Item
- [x] Indicator

### #18 Scroll Area (Skip)
- [ ] Root
- [ ] Viewport
- [ ] Scrollbar
- [ ] Thumb
- [ ] Corner

### #19 Select (Skip)
TBD

### #20 Separator
- [x] Root

### #21 Slider
- [x] Root
- [x] Track
- [x] Range
- [x] Thumb

### #22 Switch
- [x] Root
- [x] Thumb

### #23 Tabs
- [x] Root
- [x] List
- [x] Trigger
- [x] Content

### #24 Toast (Skip)
- [ ] Viewport
- [ ] Root
- [ ] Title
- [ ] Description
- [ ] Action
- [ ] Close

### #25 Toggle
- [x] Root

### #26 Toggle Group
- [x] Root
- [x] Item

### #27 Toolbar
- [x] Root
- [x] Button
- [x] Link
- [x] ToggleGroup
- [x] ToggleItem
- [x] Separator

### #28 Tooltip
- [x] Trigger
- [x] Content
- [x] Arrow

### CODE REVIEW

**Comment by khairulhaaziq** [comment]
alot of things are breaking @zernonia , it cant handle ref as usual I think
Screenshot 2023-06-28 at 9 39 52 PM
Screenshot 2023-06-28 at 9 39 45 PM

**Comment by zernonia** [comment]
thanks @khairulhaaziq . I suspect some event/event listener wasn't passed in correctly.

**Comment by khairulhaaziq** [comment]
> thanks @khairulhaaziq . I suspect some event/event listener wasn't passed in correctly. May I know which component you are wrapping the Primitive, and causing the above error ya?

in this pr ive implemented the aschild to almost everything accept the components that hasnt been built, if one you fixed the problems, you can review this

**Comment by khairulhaaziq** [comment]
> thanks @khairulhaaziq . I suspect some event/event listener wasn't passed in correctly. May I know which component you are wrapping the Primitive, and causing the above error ya?

@zernonia this might be useful aswell https://www.radix-ui.com/docs/primitives/utilities/slot

**Review by zernonia — APPROVED** [review]

**Pull request merged**
