### PR TITLE
fix(Editable): do not submit if editable is not in edit mode

### LINKED ISSUE #1036: [Bug]: Editable submits on every single click
### Environment

```bash
Node version: 20.x
Package manager: pnpm@8.6.0
Radix Vue version: 1.8.5
```

### Link to minimal reproduction

https://stackblitz.com/edit/qeo66a-zdntmx

### Steps to reproduce

1. assign event listener to the event `submit` at EditableRoot
2. click anywhere in your app
3. see event being triggered

### Describe the bug

The event is emitted on every click.

### Expected behavior

The event should only be emitted when a new value is submitted.

### Context & Screenshots (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by epr3**
Fixes #1036.

### CODE REVIEW

**Comment by Tinoooo** [comment]
Is there a practical way to remove the whole event listener (when `isEditing === true`) instead of ignoring the event? This might be more performant.

**Comment by epr3** [comment]
@Tinoooo which event listener?

**Comment by Tinoooo** [comment]
@epr3 The one in DismissableLayer.

**Comment by epr3** [comment]
Oh, got it. Will look into a solution 👍🏻

**Pull request merged**
