### PR TITLE
Move prettier to root 

### PR DESCRIPTION
**Pull request by Elliot-Alexander**
## Description
Moves the prettier installation from the package level to the root of the workspace. It also moves to having all playgrounds and docs as workspaces. Currently, for prettier, I have scoped it to just radix-vue however this can be changed to be run across all code files. 

## Related Issue

#248

## Motivation and Context

#248

## How Has This Been Tested?

Ran CI in personal fork, ran prettier format from top level to see impacted files (did not leak out of scope)

### CODE REVIEW

**Comment by zernonia** [comment]
we should move eslint into the root as well

**Comment by Elliot-Alexander** [comment]
Yeah definitely, I can update in a bit :D

**Comment by khairulhaaziq** [comment]
> Yeah definitely, I can update in a bit :D

I think [antfu's config](https://antfu.me/posts/why-not-prettier) is sufficient for our use case.

**Comment by zernonia** [comment]
> I think [antfu's config](https://antfu.me/posts/why-not-prettier) is sufficient for our use case.

Yup agree. We can only use eslint, and remove prettier entirely

**Comment by zernonia** [comment]
Thanks for the PR @Elliot-Alexander . With the help of @mukundshah  we already add `antfu/eslint-config` to root, and resolves many complications with that. 

Thus I'm closing this ticket ya 😁

**Pull request closed without merging**
